apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: renamed-guestbook-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
      - cluster: engineering-prod
      - cluster: finance-preprod
  template:
    metadata:
      name: 'renamed-{{.cluster}}-guestbook'
      annotations:
        codefresh.io/app-group: alpha
        codefresh.io/product: orphaned-product
      labels:
        env: orphaned-product
    spec:
      project: default
      source:
        path: helm-guestbook
        repoURL: https://github.com/plakyda-codefresh/argocd-example-apps
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: guestbook-appset
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false


