apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-2
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook-2
    repoURL: https://github.com/plakyda-codefresh/argocd-example-apps
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: guestbook-2
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
