apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guesbook-prod-roll-multi
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/app-long-sync-minutes: '1'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: test-dev
  sources:
    - ref: test
      path: gs-rollout-multisourced/ref
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: multisource-ref
    - path: guestbooks/guestbook-rollout-multisourced/part-one
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: hermes-prod-apps
    - path: gs-rollout-multisourced/part-two
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: multisource-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
