apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golf54-release
  labels:
    codefresh.io/entity: runtime
spec:
  project: default
  source:
    repoURL: https://github.com/plakyda-codefresh/testing.git
    targetRevision: HEAD
    path: runtime
    helm:
      releaseName: golf54-release
  destination:
    namespace: gitops-runtime
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
